# This is a file for you to write an un-named mutation. 
# Only one un-named mutation is allowed per file.
mutation {
  user_insert(data: {clerkId: "user_3Cm7EEQpDOTyoTX6zgFuyj4YQ7v", email: "mateus23ita@gmail.com", imageUrl: "https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2ltYWdlcy5jbGVyay5kZXYvb2F1dGhfZ29vZ2xlL2ltZ18zQ203RUJQclVXUm5pMzF0WU9SUUZRMjVVaE0ifQ", username: "mateus23ita"})
}